version: 2.1

commands:
  attach-with-frr:
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Install FRR
          command:
            make install

executors:
  base:
    docker:
      - image: frrouting/frr:topotests-latest
jobs:
  build:
    executor: base
    steps:
      - checkout
      - run:
          name: Compile FRR
          command: |
            ./bootstrap.sh
            ./configure \
                --enable-static-bin \
                --enable-static \
                --enable-shared \
                --with-moduledir=/usr/lib/frr/modules \
                --prefix=/usr \
                --localstatedir=/var/run/frr \
                --sbindir=/usr/lib/frr \
                --sysconfdir=/etc/frr \
                --enable-multipath=0 \
                --enable-fpm \
                --enable-sharpd \
                $EXTRA_CONFIGURE \
                --with-pkg-extra-version=-topotests
            cpu_count=$(cat /proc/cpuinfo | grep -w processor | wc -l)
            if [ $? -ne 0 ]; then
                    cpu_count=2
            fi
            echo "Building with ${cpu_count} CPUs"
            make -j${cpu_count}
      - persist_to_workspace:
          name: Persist frr to workspace
          root: /root
          paths:
            - project
  check:
    executor: base
    steps:
      - attach-with-frr
      - run:
          name: Run unittests
          command: |
            make check

workflows:
  version: 2
  build:
    jobs:
      - build
      - check:
          requires:
            - build
