version: 2.0

jobs:
  build-deb:
    docker:
      image: debian:testing
    steps:
      run:
        name: Something
        command:
          true

workflows:
  version: 2
  build:
    jobs:
      - build-deb
